# Generated by Django 4.0.4 on 2022-05-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=7),
            preserve_default=False,
        ),
    ]
